# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pip       # Specifica che si tratta di un progetto Python con requirements.txt
    directory: "/"               # Indica la directory in cui si trova il file, in questo caso la root del repository
    schedule:
      interval: weekly           # Controlla gli aggiornamenti su base settimanale (può essere anche daily o monthly)
